### ISSUE TITLE
Bug / Issuse

### ISSUE THREAD

**Issue by ExcplitBugle** [XoAlone/Roblox-Follow-Botter#2]
Sending 1 follower(s) to 564461144
Getting the CSRF Token will not work with invalid cookies.

Help im getting this error!

**Comment by XoAlone** [comment]
Are you sure that your cookie is valid?

**Comment by ExcplitBugle** [comment]
what should it look like?

**Comment by ExcplitBugle** [comment]
I think you should just update the README And explain how to excatly use it.
And give a example cookie in the roblox cookie file
it would help alot .
Like id dont even know what proxies to use

**Comment by ExcplitBugle** [comment]
Ok i fixed it and it sent the followers its pretty nice
one issuse i think this could be from the proxys im using but im getting this error
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ro.py", line 35, in <module>
    csrfRequest = requests.post('https://auth.roblox.com/v2/logout', headers=csrfHeaders, proxies=proxyObj);
  File "/home/pi/.local/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='auth.roblox.com', port=443): Max retries exceeded with url: /v2/logout (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb5d78350>: Failed to establish a new connection: [Errno 111] Connection refused')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ro.py", line 57, in <module>
    print('\x1b[31mAn error has occured! ' + e + '\x1b[0m')
TypeError: can only concatenate str (not "ProxyError") to str

```

**Comment by ExcplitBugle** [comment]
And now im back to getting the CRSF 

I think you might need to update the code or explain how do add the cookies
i added my cookies on a new line so like

```
cookie1
cookie2
cookie3
```
Please explain how this works
